name: Deploy MkDocs Documentation
      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          if [ -f CNAME ]; then
            echo "Removing CNAME file to disable custom domain redirect"
            rm CNAME
            git add -A
            git commit -m "Remove CNAME file - disable custom domain redirect" || true
            git push origin gh-pages
          else
            echo "No CNAME file found"
          fi
          git checkout main
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy with MkDocs and remove CNAME
        run: |
          mkdocs gh-deploy --force --no-jekyll
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          if [ -f CNAME ]; then
            echo "Removing CNAME file to disable custom domain redirect"
            rm CNAME
            git add -A
            git commit -m "Remove CNAME file - disable custom domain redirect" || true
            git push origin gh-pages
          else
            echo "No CNAME file found"
          fi
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
